# Generated by Django 5.1 on 2024-08-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_empleado_apellido_remove_empleado_direccion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='correo',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='telefono',
        ),
        migrations.AddField(
            model_name='empleado',
            name='nombre_completo',
            field=models.CharField(default='Sin nombre', max_length=100),
        ),
        migrations.AddField(
            model_name='empleado',
            name='rut',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
